const EVENTS = [
  {
    "id": "toge-round-7",
    "brand": "Tōge",
    "type": "Mountain Drift",
    "name": "DriftNWA Round 7 Tōge",
    "date": "November 20-22, 2026",
    "eventDays": "Friday is driver load-in, parade, and car show. Tōge runs Saturday and Sunday.",
    "venue": "Great Passion Play",
    "city": "Eureka Springs, AR",
    "address": "935 Passion Play Rd, Eureka Springs, AR 72632",
    "driverFee": "$400",
    "spectatorFee": "$10 adults. Kids 12 & under free.",
    "driverCap": "30 driver cap",
    "rideAlong": "Ride-alongs available",
    "camping": "Yes",
    "food": "Yes",
    "vendors": "Yes",
    "registration": "https://form.jotform.com/261066268983165",
    "schedule": {
      "Driver Gate": "7:00 AM",
      "Drivers Meeting": "8:30 AM",
      "Spectator Gate": "9:00 AM",
      "Track Hot": "9:30 AM",
      "Event Ends": "5:00 PM"
    },
    "logo": "assets/logos/Round 7_Toge_logo.svg",
    "hero": "assets/photos/toge_round7_13.jpg",
    "gallery": [
      "assets/photos/toge_1.jpg",
      "assets/photos/toge_3.jpg",
      "assets/photos/toge_7.jpg",
      "assets/photos/toge_11.jpg"
    ],
    "sponsors": [
      "Valino",
      "PrimeCo",
      "Justified",
      "HoldFast",
      "FastFuels",
      "BustaGrimes",
      "Speedemon",
      "BentonvilleTowing"
    ],
    "dateSort": "2026-11-20",
    "brandClass": "toge",
    "venueUrl": "https://www.greatpassionplay.org",
    "endDate": "2026-11-22"
  },
  {
    "id": "cams-rd2",
    "brand": "DriftNWA",
    "pitPass": "$20",
    "type": "Drift",
    "name": "Cams Acres w/235 Jackpot Rd2",
    "date": "June 20-21, 2026",
    "eventDays": "Two-day drift weekend with Rd2 235 Jackpot comp. $100 cash buy-in.",
    "venue": "Cams Acres Drift Complex",
    "city": "Stuart, OK",
    "address": "E1570 Rd, Stuart, OK 74570",
    "driverFee": "$200",
    "spectatorFee": "$10 adults. Kids 12 & under free.",
    "driverCap": "60 driver cap",
    "rideAlong": "Ride-alongs available",
    "camping": "Yes",
    "food": "Yes",
    "vendors": "Yes",
    "registration": "https://form.jotform.com/261115443302140",
    "schedule": {
      "Driver Gate": "7:00 AM Sat / Sun",
      "Drivers Meeting": "8:30 AM Sat / Sun",
      "Spectator Gate": "9:00 AM Sat / Sun",
      "Track Hot": "9:00 AM Sat / Sun",
      "Event Ends": "10:00 PM Sat / 4:00 PM Sun"
    },
    "logo": "assets/logos/DriftNWA_Logo_White.svg",
    "hero": "assets/photos/drift_hero_1.jpg",
    "gallery": [
      "assets/photos/drift_1.jpg",
      "assets/photos/drift_3.jpg",
      "assets/photos/drift_6.jpg"
    ],
    "sponsors": [
      "Valino",
      "PrimeCo",
      "Justified",
      "HoldFast",
      "FastFuels",
      "BustaGrimes",
      "Speedemon"
    ],
    "dateSort": "2026-06-20",
    "brandClass": "drift",
    "venueUrl": "https://www.camsacres.com",
    "endDate": "2026-06-21"
  },
  {
    "id": "cams-rd3",
    "brand": "DriftNWA",
    "pitPass": "$20",
    "type": "Drift",
    "name": "Cams Acres w/235 Jackpot Rd3",
    "date": "August 1-2, 2026",
    "eventDays": "Two-day drift weekend with Rd3 235 Jackpot comp. $100 cash buy-in.",
    "venue": "Cams Acres Drift Complex",
    "city": "Stuart, OK",
    "address": "E1570 Rd, Stuart, OK 74570",
    "driverFee": "$200",
    "spectatorFee": "$10 adults. Kids 12 & under free.",
    "driverCap": "60 driver cap",
    "rideAlong": "Ride-alongs available",
    "camping": "Yes",
    "food": "Yes",
    "vendors": "Yes",
    "registration": "https://form.jotform.com/261244611306144",
    "schedule": {
      "Driver Gate": "7:00 AM Sat / Sun",
      "Drivers Meeting": "8:30 AM Sat / Sun",
      "Spectator Gate": "9:00 AM Sat / Sun",
      "Track Hot": "9:00 AM Sat / Sun",
      "Event Ends": "10:00 PM Sat / 4:00 PM Sun"
    },
    "logo": "assets/logos/DriftNWA_Logo_White.svg",
    "hero": "assets/photos/drift_hero_2.jpg",
    "gallery": [
      "assets/photos/drift_1.jpg",
      "assets/photos/drift_3.jpg",
      "assets/photos/drift_6.jpg"
    ],
    "sponsors": [
      "Valino",
      "PrimeCo",
      "Justified",
      "HoldFast",
      "FastFuels",
      "BustaGrimes",
      "Speedemon"
    ],
    "dateSort": "2026-08-01",
    "brandClass": "drift",
    "venueUrl": "https://www.camsacres.com",
    "endDate": "2026-08-02"
  },
  {
    "id": "grip-september",
    "brand": "GripNWA",
    "type": "AutoX",
    "name": "September 12th Event",
    "date": "September 12, 2026",
    "eventDays": "AutoX event at Drake Field.",
    "venue": "Drake Field",
    "city": "Fayetteville, AR",
    "address": "317 W Ernest Lancaster Dr, Fayetteville, AR 72701",
    "driverFee": "$60",
    "spectatorFee": "$5 adults. Kids 12 & under free.",
    "driverCap": "80 driver cap",
    "rideAlong": "Ride-alongs available",
    "camping": "No",
    "food": "Yes",
    "vendors": "Yes",
    "registration": "https://form.jotform.com/261465362797166",
    "schedule": {
      "Driver Gate": "8:00 AM",
      "Drivers Meeting": "9:00 AM",
      "Spectator Gate": "9:00 AM",
      "Track Hot": "9:30 AM",
      "Event Ends": "5:00 PM"
    },
    "logo": "assets/logos/GripNWA_Logo_White.svg",
    "hero": "assets/photos/grip_1.jpg",
    "gallery": [
      "assets/photos/grip_1.jpg",
      "assets/photos/grip_2.jpg",
      "assets/photos/grip_11.jpg"
    ],
    "sponsors": [
      "Valino",
      "RealClean",
      "PrimeCo",
      "Justified",
      "HoldFast",
      "FastFuels",
      "BustaGrimes",
      "Speedemon"
    ],
    "dateSort": "2026-09-12",
    "brandClass": "grip",
    "venueUrl": "",
    "registrationDeadline": "Wednesday before the event at 6:00 PM",
    "endDate": "2026-09-12"
  },
  {
    "id": "grip-october",
    "brand": "GripNWA",
    "type": "AutoX",
    "name": "October 17th Event",
    "date": "October 17, 2026",
    "eventDays": "AutoX event at Drake Field.",
    "venue": "Drake Field",
    "city": "Fayetteville, AR",
    "address": "317 W Ernest Lancaster Dr, Fayetteville, AR 72701",
    "driverFee": "$60",
    "spectatorFee": "$5 adults. Kids 12 & under free.",
    "driverCap": "80 driver cap",
    "rideAlong": "Ride-alongs available",
    "camping": "No",
    "food": "Yes",
    "vendors": "Yes",
    "registration": "https://form.jotform.com/261465042687159",
    "schedule": {
      "Driver Gate": "8:00 AM",
      "Drivers Meeting": "9:00 AM",
      "Spectator Gate": "9:00 AM",
      "Track Hot": "9:30 AM",
      "Event Ends": "5:00 PM"
    },
    "logo": "assets/logos/GripNWA_Logo_White.svg",
    "hero": "assets/photos/grip_8.jpg",
    "gallery": [
      "assets/photos/grip_1.jpg",
      "assets/photos/grip_2.jpg",
      "assets/photos/grip_11.jpg"
    ],
    "sponsors": [
      "Valino",
      "RealClean",
      "PrimeCo",
      "Justified",
      "HoldFast",
      "FastFuels",
      "BustaGrimes",
      "Speedemon"
    ],
    "dateSort": "2026-10-17",
    "brandClass": "grip",
    "venueUrl": "",
    "registrationDeadline": "Wednesday before the event at 6:00 PM",
    "endDate": "2026-10-17"
  },
  {
    "id": "drift-october",
    "brand": "DriftNWA",
    "pitPass": "$20",
    "type": "Drift",
    "name": "October 18th w/235 Jackpot Rd4",
    "date": "October 18, 2026",
    "eventDays": "Rd4 235 Jackpot comp. $100 cash buy-in. Pit pass $20, ride alongs available.",
    "venue": "Drake Field",
    "city": "Fayetteville, AR",
    "address": "317 W Ernest Lancaster Dr, Fayetteville, AR 72701",
    "driverFee": "$90",
    "spectatorFee": "$5 adults. Kids 12 & under free.",
    "driverCap": "50 driver cap",
    "rideAlong": "$20 Pit Pass",
    "camping": "No",
    "food": "Yes",
    "vendors": "Yes",
    "registration": "https://form.jotform.com/261464752746162",
    "schedule": {
      "Driver Gate": "8:00 AM",
      "Drivers Meeting": "9:00 AM",
      "Spectator Gate": "9:00 AM",
      "Track Hot": "9:30 AM",
      "Event Ends": "5:00 PM"
    },
    "logo": "assets/logos/DriftNWA_Logo_White.svg",
    "hero": "assets/photos/drift_1.jpg",
    "gallery": [
      "assets/photos/drift_1.jpg",
      "assets/photos/drift_3.jpg",
      "assets/photos/drift_6.jpg"
    ],
    "sponsors": [
      "Valino",
      "RealClean",
      "PrimeCo",
      "Justified",
      "HoldFast",
      "FastFuels",
      "BustaGrimes",
      "Speedemon"
    ],
    "dateSort": "2026-10-18",
    "brandClass": "drift",
    "venueUrl": "",
    "endDate": "2026-10-18"
  }
];
const SPONSOR_LOGOS = {
  "Valino": "assets/sponsors/Valino_Logo.svg",
  "PrimeCo": "assets/sponsors/PrimeCo_Logo.svg",
  "Justified": "assets/sponsors/Justified_Logo.svg",
  "HoldFast": "assets/sponsors/HoldFast_Logo.svg",
  "FastFuels": "assets/sponsors/FastFuels_Logo.png",
  "BustaGrimes": "assets/sponsors/BustaGrimes_Logo.svg",
  "Speedemon": "assets/sponsors/Speedemon_Logo.svg",
  "BentonvilleTowing": "assets/sponsors/BentonvilleTowing_Logo.svg",
  "RealClean": "assets/sponsors/RealClean_Logo.png"
};
const SPONSOR_URLS = {
  "Valino": "https://www.valinotires.com",
  "RealClean": "https://www.realcleanaircraft.com",
  "PrimeCo": "https://primecoexc.com",
  "Justified": "https://justifiedproformance.com",
  "HoldFast": "https://holdfast-usa.com",
  "FastFuels": "https://fastfuel.live",
  "BustaGrimes": "https://bustagrimes.pro",
  "Speedemon": "https://speedemon.co",
  "BentonvilleTowing": ""
};